### ISSUE TITLE
Close dialog don't highlight selected option when using `tab`

### ISSUE THREAD

**Issue by hasecilu** [obelisk79/OpenDark#25] opened 2023-10-29 19:58 UTC
- The selected option is only highlighted when the cursor is over the option.
- Using the `Tab` key moves the selected option but there is no visual feedback, it's like a russian roulette.
Using behave-dark
![image](https://github.com/obelisk79/OpenDark/assets/53124818/6caf2224-437e-4a2e-a25a-4221d8f5d44b)
Using OpenDark
![image](https://github.com/obelisk79/OpenDark/assets/53124818/8ca3ddb6-88f3-439e-904c-8f9dd9159d68)

**Comment by obelisk79** [comment] 2023-10-30 10:51
should be fixed now, update and let me know if the problem is still there

**Closed** 2023-10-30 10:51 UTC

**Comment by hasecilu** [comment] 2023-10-30 15:47
It's working, thanks for the fix.
